In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df_b2 = pd.read_csv('/content/drive/MyDrive/perovskite/synthetic_data_b2.csv')
df_b3 = pd.read_csv("/content/drive/MyDrive/perovskite/synthetic_data_b3.csv")

In [ ]:
df = pd.concat([df_b2,df_b3],ignore_index=True,axis=0)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13088 entries, 0 to 13087
Data columns (total 34 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    13088 non-null  int64
 1   formula       13088 non-null  object
 2   A             13088 non-null  object
 3   B1            13088 non-null  object
 4   B3            13088 non-null  object
 5   X             13088 non-null  object
 6   R-A(pm)       13088 non-null  float64
 7   I-A(kJ/mol)   13088 non-null  float64
 8   V-A           13088 non-null  float64
 9   P-A           13088 non-null  float64
 10  E-A(kJ/mol)   13088 non-null  float64
 11  N-A           13088 non-null  float64
 12  R-B1(pm)      13088 non-null  float64
 13  X-B1(kJ/mol)  13088 non-null  float64
 14  V-B1          13088 non-null  float64
 15  P-B1          13088 non-null  float64
 16  E-B1(kJ/mol)  13088 non-null  float64
 17  N-B1          13088 non-null  float64
 18  R-B3(pm)      13088 non-null  float64
 19  X-B3(kJ/mol)  13088 non-null  float64
 20  V-B3          13088 non-null  float64
 21  P-B3          13088 non-null  float64
 22  E-B3(kJ/mol)  13088 non-null  float64
 23  N-B3          13088 non-null  float64
 24  R-X(pm)       13088 non-null  float64
 25  X-X(kJ/mol)   13088 non-null  float64
 26  V-X           13088 non-null  float64
 27  P-X           13088 non-null  float64
 28  E-X(kJ/mol)   13088 non-null  float64
 29  A-X(kJ/mol)   13088 non-null  float64
 30  N-X           13088 non-null  float64
 31  BE(A-X)       11813 non-null  float64
 32  BE(B1-X)      11275 non-null  float64
 33  BE(B3-X)      10994 non-null  float64
dtypes: float64(28), int64(1), object(5)
memory usage: 3.4+ MB

## Predicting Band Gap

In [ ]:
df.drop(columns=['Unnamed: 0'],inplace=True)

In [ ]:
column_drop = ['V-A', 'P-A', 'E-A(kJ/mol)','N-A', 'X-B1(kJ/mol)','V-X','A-X(kJ/mol)','formula','A','B1','B3','X']

In [ ]:
df_copy = df.drop(columns=column_drop)

In [ ]:
import joblib

In [ ]:
#load model
moodel_path = '/content/drive/MyDrive/colab-model/XGBR_deap_perovskites25-6-25.joblib'
model = joblib.load(moodel_path)
print("\nModel loaded successfully.")

Model loaded successfully.

In [ ]:
df_copy.reset_index(drop=True, inplace=True)
df.reset_index(drop=True, inplace=True)

In [ ]:
# scaler = joblib.load('/content/drive/MyDrive/colab-model/XGBR_deap_perovskites_scaler.pkl')

In [ ]:
# df_scaled = scaler.transform(df_copy)

In [ ]:
y_pred = model.predict(df_copy)

In [ ]:
len(y_pred)

13088

In [ ]:
df["band_gap"] = y_pred

## Predicting Stability

In [ ]:
cols = list(df.columns)
cols.insert(0, cols.pop(cols.index('band_gap')))
df = df.loc[:, cols]
df.head()

,band_gap,formula,A,B1,B3,X,R-A(pm),I-A(kJ/mol),V-A,P-A,...,R-X(pm),X-X(kJ/mol),V-X,P-X,E-X(kJ/mol),A-X(kJ/mol),N-X,BE(A-X),BE(B1-X),BE(B3-X)
0,2.952501,Li2PbPbF6,Li,Pb,Pb,F,76.0,520.2,1.0,164.1,...,133.0,3.98,7.0,3.74,79.08,-328.0,9.0,574.9,356.0,356.0
1,2.274036,Li2PbPbCl6,Li,Pb,Pb,Cl,76.0,520.2,1.0,164.1,...,181.0,3.16,7.0,14.60,121.80,-349.0,17.0,470.7,301.0,301.0
2,1.681199,Li2PbPbBr6,Li,Pb,Pb,Br,76.0,520.2,1.0,164.1,...,196.0,2.96,7.0,21.60,111.70,-324.0,35.0,423.0,247.0,247.0
3,1.746967,Li2PbPbI6,Li,Pb,Pb,I,76.0,520.2,1.0,164.1,...,220.0,2.66,7.0,32.90,106.70,-295.0,53.0,352.0,197.0,197.0
4,2.640710,Li2PbSnF6,Li,Pb,Sn,F,76.0,520.2,1.0,164.1,...,133.0,3.98,7.0,3.74,79.08,-328.0,9.0,574.9,356.0,466.5

In [ ]:
df.columns

Index(['band_gap', 'formula', 'A', 'B1', 'B3', 'X', 'R-A(pm)', 'I-A(kJ/mol)',
       'V-A', 'P-A', 'E-A(kJ/mol)', 'N-A', 'R-B1(pm)', 'X-B1(kJ/mol)', 'V-B1',
       'P-B1', 'E-B1(kJ/mol)', 'N-B1', 'R-B3(pm)', 'X-B3(kJ/mol)', 'V-B3',
       'P-B3', 'E-B3(kJ/mol)', 'N-B3', 'R-X(pm)', 'X-X(kJ/mol)', 'V-X', 'P-X',
       'E-X(kJ/mol)', 'A-X(kJ/mol)', 'N-X', 'BE(A-X)', 'BE(B1-X)', 'BE(B3-X)',
       'stable', 'Tolerance_Factor', 'Octahedral_Factor'],
      dtype='object')

In [ ]:
column_to_drop = ['formula','A','B1',"B3",'X','R-B1(pm)', 'V-B1', 'P-B1', 'N-B1', 'R-B3(pm)', 'X-B3(kJ/mol)', 'V-B3',
       'E-B3(kJ/mol)', 'N-B3', 'P-X', 'A-X(kJ/mol)', 'N-X', 'BE(A-X)',
       'BE(B1-X)']

In [ ]:
df_stability = df.drop(columns=column_to_drop,axis=1)

In [ ]:
df_stability.drop(columns=['stable', 'Tolerance_Factor', 'Octahedral_Factor'],inplace=True)

In [ ]:
# loading stability scaler and model
moodel_path = '/content/drive/MyDrive/colab-model/Decision_tree_stability0.025_perovskites.joblib'
model_stability = joblib.load(moodel_path)
# scaler_stability = joblib.load('/content/drive/MyDrive/colab-model/XGB_stability0.025_perovskites_scaler.pkl')

In [ ]:
# df_stability_scaled = scaler_stability.transform(df_stability)

In [ ]:
y_pred_stability = model_stability.predict(df_stability)

In [ ]:
df['stable'] = y_pred_stability

In [ ]:
df['stable'].value_counts()

stable
0    7161
1    5927
Name: count, dtype: int64

## filtering data set

In [ ]:
df.to_csv('/content/drive/MyDrive/Colab-dataset/synthetic0.025_data_predicted.csv')

In [ ]:
df['Tolerance_Factor'] = (df['R-A(pm)'] + df['R-X(pm)']) / (np.sqrt(2) * ((df['R-B1(pm)'] + df['R-B3(pm)']) / 2 + df['R-X(pm)']))

In [ ]:
df['Octahedral_Factor'] = (df['R-B1(pm)'] + df['R-B3(pm)']) / (2 * df['R-X(pm)'])

In [ ]:
df.head()

,band_gap,formula,A,B1,B3,X,R-A(pm),I-A(kJ/mol),V-A,P-A,...,P-X,E-X(kJ/mol),A-X(kJ/mol),N-X,BE(A-X),BE(B1-X),BE(B3-X),stable,Tolerance_Factor,Octahedral_Factor
0,2.952501,Li2PbPbF6,Li,Pb,Pb,F,76.0,520.2,1.0,164.1,...,3.74,79.08,-328.0,9.0,574.9,356.0,356.0,0,0.586450,0.894737
1,2.274036,Li2PbPbCl6,Li,Pb,Pb,Cl,76.0,520.2,1.0,164.1,...,14.60,121.80,-349.0,17.0,470.7,301.0,301.0,0,0.605755,0.657459
2,1.681199,Li2PbPbBr6,Li,Pb,Pb,Br,76.0,520.2,1.0,164.1,...,21.60,111.70,-324.0,35.0,423.0,247.0,247.0,0,0.610581,0.607143
3,1.746967,Li2PbPbI6,Li,Pb,Pb,I,76.0,520.2,1.0,164.1,...,32.90,106.70,-295.0,53.0,352.0,197.0,197.0,0,0.617415,0.540909
4,2.640710,Li2PbSnF6,Li,Pb,Sn,F,76.0,520.2,1.0,164.1,...,3.74,79.08,-328.0,9.0,574.9,356.0,466.5,0,0.587616,0.890977

In [ ]:
df[df['formula']=='Cs2MnCdCl6']

,band_gap,formula,A,B1,B3,X,R-A(pm),I-A(kJ/mol),V-A,P-A,...,P-X,E-X(kJ/mol),A-X(kJ/mol),N-X,BE(A-X),BE(B1-X),BE(B3-X),stable,Tolerance_Factor,Octahedral_Factor
6443,2.173364,Cs2MnCdCl6,Cs,Mn,Cd,Cl,167.0,375.7,1.0,400.0,...,14.6,121.8,-349.0,17.0,439.0,361.0,206.7,1,0.939211,0.447514

In [ ]:
filtered_df = df[
    (df['band_gap'] >= 0.65) & (df['band_gap'] <= 1.6) &
    (df['Octahedral_Factor'] >= 0.44) & (df['Octahedral_Factor'] <= 0.9) &
    (df['Tolerance_Factor'] >= 0.82) & (df['Tolerance_Factor'] <= 1.08) &
    (df['stable'] == 1)
]
print(filtered_df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 312 entries, 1706 to 12301
Data columns (total 37 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   band_gap           312 non-null    float32
 1   formula            312 non-null    object
 2   A                  312 non-null    object
 3   B1                 312 non-null    object
 4   B3                 312 non-null    object
 5   X                  312 non-null    object
 6   R-A(pm)            312 non-null    float64
 7   I-A(kJ/mol)        312 non-null    float64
 8   V-A                312 non-null    float64
 9   P-A                312 non-null    float64
 10  E-A(kJ/mol)        312 non-null    float64
 11  N-A                312 non-null    float64
 12  R-B1(pm)           312 non-null    float64
 13  X-B1(kJ/mol)       312 non-null    float64
 14  V-B1               312 non-null    float64
 15  P-B1               312 non-null    float64
 16  E-B1(kJ/mol)       312 non-null    float64
 17  N-B1               312 non-null    float64
 18  R-B3(pm)           312 non-null    float64
 19  X-B3(kJ/mol)       312 non-null    float64
 20  V-B3               312 non-null    float64
 21  P-B3               312 non-null    float64
 22  E-B3(kJ/mol)       312 non-null    float64
 23  N-B3               312 non-null    float64
 24  R-X(pm)            312 non-null    float64
 25  X-X(kJ/mol)        312 non-null    float64
 26  V-X                312 non-null    float64
 27  P-X                312 non-null    float64
 28  E-X(kJ/mol)        312 non-null    float64
 29  A-X(kJ/mol)        312 non-null    float64
 30  N-X                312 non-null    float64
 31  BE(A-X)            304 non-null    float64
 32  BE(B1-X)           272 non-null    float64
 33  BE(B3-X)           284 non-null    float64
 34  stable             312 non-null    int64
 35  Tolerance_Factor   312 non-null    float64
 36  Octahedral_Factor  312 non-null    float64
dtypes: float32(1), float64(30), int64(1), object(5)
memory usage: 91.4+ KB
None

In [ ]:
filtered_df[filtered_df['formula'] == 'Cs2SnMgBr6']

Empty DataFrame
Columns: [band_gap, formula, A, B1, B3, X, R-A(pm), I-A(kJ/mol), V-A, P-A, E-A(kJ/mol), N-A, R-B1(pm), X-B1(kJ/mol), V-B1, P-B1, E-B1(kJ/mol), N-B1, R-B3(pm), X-B3(kJ/mol), V-B3, P-B3, E-B3(kJ/mol), N-B3, R-X(pm), X-X(kJ/mol), V-X, P-X, E-X(kJ/mol), A-X(kJ/mol), N-X, BE(A-X), BE(B1-X), BE(B3-X), stable, Tolerance_Factor, Octahedral_Factor, rb, new_tau]
Index: []

[0 rows x 39 columns]

In [ ]:
import math
def calculate_new_tau(rx, rb, ra, na):
    try:
        if ra <= 0 or rb <= 0 or rx <= 0 or math.isclose(ra, rb):
            return np.nan
        term1 = rx / rb
        term2 = na * (na - (ra / rb) / math.log(ra / rb))
        tau = term1 - term2
        return tau
    except:
        return np.nan

In [ ]:
filtered_df['rb'] = (filtered_df['R-B1(pm)'] + filtered_df['R-B3(pm)']) / 2
na = 1
filtered_df['new_tau'] = filtered_df.apply(lambda row: calculate_new_tau(row['R-X(pm)'], row['rb'], row['R-A(pm)'], na), axis=1)

/tmp/ipython-input-26-1373977287.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['rb'] = (filtered_df['R-B1(pm)'] + filtered_df['R-B3(pm)']) / 2
/tmp/ipython-input-26-1373977287.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['new_tau'] = filtered_df.apply(lambda row: calculate_new_tau(row['R-X(pm)'], row['rb'], row['R-A(pm)'], na), axis=1)

In [ ]:
final_df = filtered_df[filtered_df['new_tau'] < 4.18]

In [ ]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 115 entries, 3074 to 12301
Data columns (total 39 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   band_gap           115 non-null    float32
 1   formula            115 non-null    object
 2   A                  115 non-null    object
 3   B1                 115 non-null    object
 4   B3                 115 non-null    object
 5   X                  115 non-null    object
 6   R-A(pm)            115 non-null    float64
 7   I-A(kJ/mol)        115 non-null    float64
 8   V-A                115 non-null    float64
 9   P-A                115 non-null    float64
 10  E-A(kJ/mol)        115 non-null    float64
 11  N-A                115 non-null    float64
 12  R-B1(pm)           115 non-null    float64
 13  X-B1(kJ/mol)       115 non-null    float64
 14  V-B1               115 non-null    float64
 15  P-B1               115 non-null    float64
 16  E-B1(kJ/mol)       115 non-null    float64
 17  N-B1               115 non-null    float64
 18  R-B3(pm)           115 non-null    float64
 19  X-B3(kJ/mol)       115 non-null    float64
 20  V-B3               115 non-null    float64
 21  P-B3               115 non-null    float64
 22  E-B3(kJ/mol)       115 non-null    float64
 23  N-B3               115 non-null    float64
 24  R-X(pm)            115 non-null    float64
 25  X-X(kJ/mol)        115 non-null    float64
 26  V-X                115 non-null    float64
 27  P-X                115 non-null    float64
 28  E-X(kJ/mol)        115 non-null    float64
 29  A-X(kJ/mol)        115 non-null    float64
 30  N-X                115 non-null    float64
 31  BE(A-X)            110 non-null    float64
 32  BE(B1-X)           96 non-null     float64
 33  BE(B3-X)           110 non-null    float64
 34  stable             115 non-null    int64
 35  Tolerance_Factor   115 non-null    float64
 36  Octahedral_Factor  115 non-null    float64
 37  rb                 115 non-null    float64
 38  new_tau            115 non-null    float64
dtypes: float32(1), float64(32), int64(1), object(5)
memory usage: 35.5+ KB

In [ ]:
final_df['A'].value_counts()

A
Cs    81
Rb    14
K     11
Au     5
Ag     4
Name: count, dtype: int64

In [ ]:
#pt , be,

In [ ]:
## droping Ag Au and Pb

final_df = final_df[~((final_df['A'].str.contains('Ag')) | (final_df['B1'].str.contains('Ag')) | (final_df['B3'].str.contains('Ag')))]
final_df = final_df[~((final_df['A'].str.contains('Pb')) | (final_df['B1'].str.contains('Pb')) | (final_df['B3'].str.contains('Pb')))]
final_df = final_df[~((final_df['A'].str.contains('Au')) | (final_df['B1'].str.contains('Au')) | (final_df['B3'].str.contains('Au')))]
final_df = final_df[~((final_df['A'].str.contains('Pt')) | (final_df['B1'].str.contains('Pt')) | (final_df['B3'].str.contains('Pt')))]
final_df = final_df[~((final_df['A'].str.contains('Be')) | (final_df['B1'].str.contains('Be')) | (final_df['B3'].str.contains('Be')))]

In [ ]:
print(len(final_df))

77

In [ ]:
print(final_df['formula'])

3074       K2GeCuF6
3518       K2MnFeF6
3806       K2CuCaF6
3838       K2CuZnF6
3858       K2CuCdF6
            ...
7179     Cs2CdCuCl6
7186      Cs2CdPdF6
7187     Cs2CdPdCl6
7188     Cs2CdPdBr6
12241    Cs2CuBiCl6
Name: formula, Length: 77, dtype: object

In [ ]:
final_df[final_df['formula'] == "Cs2MnCdCl6"]

Empty DataFrame
Columns: [band_gap, formula, A, B1, B3, X, R-A(pm), I-A(kJ/mol), V-A, P-A, E-A(kJ/mol), N-A, R-B1(pm), X-B1(kJ/mol), V-B1, P-B1, E-B1(kJ/mol), N-B1, R-B3(pm), X-B3(kJ/mol), V-B3, P-B3, E-B3(kJ/mol), N-B3, R-X(pm), X-X(kJ/mol), V-X, P-X, E-X(kJ/mol), A-X(kJ/mol), N-X, BE(A-X), BE(B1-X), BE(B3-X), stable, Tolerance_Factor, Octahedral_Factor, rb, new_tau]
Index: []

[0 rows x 39 columns]

In [ ]:
'''I've found additional calculated band gap values for some of the double perovskites. K2FeZnF6 is estimated at 2.18 eV, K2FeCdF6 at 2.28 eV, K2CoGeF6 at 2.17 eV, K2CoCaF6 at 2.18 eV, K2NiMnF6 at 1.89 eV, K2NiZnF6 at 2.21 eV, K2NiCdF6 at 2.25 eV, K2PtGeF6 at 2.27 eV, K2PtMnF6 at 2.26 eV, Rb2BeCuF6 at 2.93 eV (based on a similar compound), Rb2FeSnF6 at 2.21 eV, Rb2FeGeF6 at 2.20 eV, Rb2FeMgF6 at 2.20 eV, Rb2FeZnF6 at 2.21 eV, Rb2FeCdF6 at 2.25 eV, Rb2CoSnF6 at 1.79 eV, Rb2CoMgF6 at 2.20 eV, Rb2CoZnF6 at 2.21 eV, Rb2NiPbF6 at 1.56 eV, Rb2NiFeF6 at 1.62 eV, Rb2PtMgF6 at 2.20 eV, Rb2PtCoF6 at 4.872 eV, Rb2PtZnF6 at 2.21 eV, Rb2PtCdF6 at 2.25 eV, Cs2PbFeBr6 at 2.05 eV, Cs2PbNiBr6 with Gallium substitution having a band gap around 1.9 eV, Cs2GePtF6 at 2.06 eV (for a related compound), Cs2MnCdCl6 at 2.1 eV (for a related compound), Cs2FePbF6 at 2.21 eV (for a related compound), Cs2FeFeF6 at 1.72 eV (for a related compound), Cs2FeCdF6 at 2.25 eV, Cs2CoFeF6 at 1.72 eV (for a related compound), Cs2CoCoF6 at 1.72 eV (for a related compound), Cs2CoZnF6 at 2.21 eV, Cs2NiFeF6 at 1.62 eV, Cs2CuMnF6 at 0.949 eV (potentially underestimated), Cs2PtFeF6 having a band gap between 1.4 eV and 2.6 eV (for a related compound), Cs2CdCdBr6 at 2.25 eV, and Cs2CuScF6 at 0.949 eV (potentially underestimated).'''

In [ ]:
final_df.columns

Index(['band_gap', 'formula', 'A', 'B1', 'B3', 'X', 'R-A(pm)', 'I-A(kJ/mol)',
       'V-A', 'P-A', 'E-A(kJ/mol)', 'N-A', 'R-B1(pm)', 'X-B1(kJ/mol)', 'V-B1',
       'P-B1', 'E-B1(kJ/mol)', 'N-B1', 'R-B3(pm)', 'X-B3(kJ/mol)', 'V-B3',
       'P-B3', 'E-B3(kJ/mol)', 'N-B3', 'R-X(pm)', 'X-X(kJ/mol)', 'V-X', 'P-X',
       'E-X(kJ/mol)', 'A-X(kJ/mol)', 'N-X', 'BE(A-X)', 'BE(B1-X)', 'BE(B3-X)',
       'stable', 'Tolerance_Factor', 'Octahedral_Factor', 'rb', 'new_tau'],
      dtype='object')

In [ ]:
short_final_df = final_df.drop(columns=[ 'R-A(pm)', 'I-A(kJ/mol)',
       'V-A', 'P-A', 'E-A(kJ/mol)', 'N-A', 'R-B1(pm)', 'X-B1(kJ/mol)', 'V-B1',
       'P-B1', 'E-B1(kJ/mol)', 'N-B1', 'R-B3(pm)', 'X-B3(kJ/mol)', 'V-B3',
       'P-B3', 'E-B3(kJ/mol)', 'N-B3', 'R-X(pm)', 'X-X(kJ/mol)', 'V-X', 'P-X',
       'E-X(kJ/mol)', 'A-X(kJ/mol)', 'N-X', 'BE(A-X)', 'BE(B1-X)', 'BE(B3-X)',
       'stable','rb',])

In [ ]:
short_final_df.to_csv('/content/drive/MyDrive/Colab-dataset/short_final_df(b0.65,e0.025).csv')